=== cymtu/NETBEANS_MYSQL_TEST/files_for_test/pers.dtd
<!ELEMENT persons (person)*>
<!ELEMENT person (name,address,notation)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT notation (#PCDATA)>

=== cymtu/NETBEANS_MYSQL_TEST/files_for_test/test4.xml
<?xml version="1.0" encoding="windows-1251"?>
<!DOCTYPE persons SYSTEM "pers.dtd">
<persons>
  <person>
    <name>Дядя Федор</name>
	<address>Простоквашино</address>
	<notation>очень самостоятельный городской мальчик</notation>
  </person>
  <person>
    <name>кот Матроскин</name>
	<address>Простоквашино</address>
	<notation>умеет вышывать на машинке</notation>
  </person>
  <person>
    <name>пес Шарик</name>
	<address>Простоквашино</address>
	<notation>рисует фигвамы на печах</notation>
  </person>  
</persons>
